version: '3.8'
services:
  frontend:
    image: paul-frontend:latest
    container_name: frontend
    ports:
      - '3001:3001'
    volumes:
      - './exam1:/app'
      - '/app/node_modules'
    networks:
      - mynetwork
    depends_on:
      - redis
      - exam1server 
  exam1server:
    build: ./exam1server
    container_name: exam1server_c
    ports:
      - '3000:3000'
    volumes:
      - './exam1server:/app'
    networks:
      - mynetwork
    depends_on:
      - redis
  redis:
    container_name: redis-service
    image: 'redis:latest'
    restart: always
    networks:
      - mynetwork
networks:
  mynetwork:
    name: mynetwork
    driver: bridge
