version: '3.8'
services:
  frontend:
    image: paul-frontend:latest
    container_name: frontend
    ports:
      - '3001:3001'
    env_file:
      - frontend.env  
    networks:
      - mynetwork
    depends_on:
      - redis
      - backend 
  backend:
    image: paul-backend:latest
    container_name: backend
    ports:
      - '3000:3000'   
    env_file:
      - backend.env  
    networks:
      - mynetwork
    depends_on:
      - redis
  redis:
    container_name: redis-service
    image: 'redis:latest'
    restart: always
    networks:
      - mynetwork
networks:
  mynetwork:
    name: mynetwork
    driver: bridge
